site_name: Tempo
site_url: https://tempo-organization.github.io/tempo-cli/

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.indexes
    - content.code.copy
    - content.tabs.link
  icon:
    logo: fontawesome/solid/t
    repo: fontawesome/brands/github
  palette:
    # Auto toggle for the user to switch between modes based on system preference
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to system preference

    # Default Dark Mode (for users who have dark mode preference)
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Dark mode
      primary: deep purple
      accent: cyan

    # Default Light Mode (for users who have light mode preference)
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/weather-night
        name: Light mode
      primary: deep purple
      accent: cyan

nav:
  - Home: index.md
  - Introduction:
      - getting_started.md
      - help.md
  - Tutorials: tutorials.md
  - Reference:
            - "reference/index.md"
            - Commands:
                    - commands/index.md
                    - clean:
                        - "commands/clean/index.md"
                        - build: commands/clean/build.md
                        - cooked: commands/clean/cooked.md
                        - from_file_list: commands/clean/from_file_list.md
                        - full: commands/clean/full.md
                        - game: commands/clean/game.md
                        - resync_dir_with_repo: commands/clean/resync_dir_with_repo.md
                    - collection:
                        - "commands/collection/index.md"
                        - add_collections_to_mod_entry: commands/collection/add_collections_to_mod_entry.md
                        - add_content_lines_to_collection: commands/collection/add_content_lines_to_collection.md
                        - create_collection: commands/collection/create_collection.md
                        - delete_collection: commands/collection/delete_collection.md
                        - disable_collection: commands/collection/disable_collection.md
                        - enable_collection: commands/collection/enable_collection.md
                        - remove_collections_from_mod_entry: commands/collection/remove_collections_from_mod_entry.md
                        - remove_content_lines_from_collection: commands/collection/remove_content_lines_from_collection.md
                        - rename_collection: commands/collection/rename_collection.md
                        - set_collection_type_from_collection_path: commands/collection/set_collection_type_from_collection_path.md
                        - set_color_from_collection_path: commands/collection/set_color_from_collection_path.md
                        - set_file_version_from_collection_path: commands/collection/set_file_version_from_collection_path.md
                        - set_guid_from_collection_path: commands/collection/set_guid_from_collection_path.md
                        - set_parent_guid_from_collection_path: commands/collection/set_parent_guid_from_collection_path.md
                    - dump:
                        - "commands/dump/index.md"
                        - aes_keys: commands/dump/aes_keys.md
                        - build_configuration: commands/dump/build_configuration.md
                        - engine_version: commands/dump/engine_version.md
                        - jmap: commands/dump/jmap.md
                        - script_objects: commands/dump/script_objects.md
                    - ini:
                        - "commands/ini/index.md"
                        - add_meta_data_tags_for_asset_registry_to_unreal_ini: commands/ini/add_meta_data_tags_for_asset_registry_to_unreal_ini.md
                        - remove_meta_data_tags_for_asset_registry_from_unreal_ini: commands/ini/remove_meta_data_tags_for_asset_registry_from_unreal_ini.md
                    - init: commands/init.md
                    - json:
                        - "commands/json/index.md"
                        - add: commands/json/add.md
                        - remove: commands/json/remove.md
                    - mod:
                        - "commands/json/index.md"
                        - add_mod: commands/mod/add_mod.md
                        - disable_mod: commands/mod/disable_mod.md
                        - disable_mods: commands/mod/disable_mods.md
                        - enable_mod: commands/mod/enable_mod.md
                        - enable_mod: commands/mod/enable_mods.md
                        - generate_mod_releases: commands/mod/generate_mod_releases.md
                        - generate_mod_releases_all: commands/mod/generate_mod_releases_all.md
                        - generate_mods: commands/mod/generate_mods.md
                        - generate_mods_all: commands/mod/generate_mods_all.md
                        - remove_mod: commands/mod/remove_mod.md
                    - run:
                        - "commands/run/index.md"
                        - add_module_to_descriptor: commands/run/add_module_to_descriptor.md
                        - add_plugin_to_descriptor: commands/run/add_plugin_to_descriptor.md
                        - engine: commands/run/engine.md
                        - full_run: commands/run/full_run.md
                        - full_run_all: commands/run/full_run_all.md
                        - game: commands/run/game.md
                        - kismet_analyze_directory: commands/run/kismet_analyze_directory.md
                        - remove_modules_from_descriptor: commands/run/remove_modules_from_descriptor.md
                        - remove_plugins_from_descriptor: commands/run/remove_plugins_from_descriptor.md
                        - test_mods: commands/run/test_mods.md
                        - test_mods_all: commands/run/test_mods_all.md
                    - tui: commands/tui.md
                    - toml:
                        - "commands/toml/index.md"
                        - add: commands/toml/add.md
                        - remove: commands/toml/remove.md
                    - tool:
                        - "commands/tool/index.md"
                        - install:
                            - "commands/tool/install/index.md"
                            - fmodel: commands/tool/install/fmodel.md
                            - kismet_analyzer: commands/tool/install/kismet_analyzer.md
                            - spaghetti: commands/tool/install/spaghetti.md
                            - stove: commands/tool/install/stove.md
                            - uasset_gui: commands/tool/install/uasset_gui.md
                            - umodel: commands/tool/install/umodel.md
                    - uplugin:
                        - "commands/uplugin/index.md"
                        - build: commands/uplugin/build.md
                        - generate: commands/uplugin/generate.md
                        - remove: commands/uplugin/remove.md
                    - uproject:
                        - "commands/uproject/index.md"
                        - build: commands/uproject/build.md
                        - cook: commands/uproject/cook.md
                        - generate: commands/uproject/generate.md
                        - package: commands/uproject/package.md
                        - resave_packages_and_fix_up_redirectors: commands/uproject/resave_packages_and_fix_up_redirectors.md
  - FAQ: faq.md
  - Roadmap: to_do_list.md
  - Community: community.md

extra_css:
  - stylesheets/extra.css

repo_url: https://github.com/Tempo-Organization/tempo-cli
repo_name: tempo

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Tempo-Organization/tempo-cli
      name: Tempo on Github
    - icon: fontawesome/brands/discord
      link: https://discord.gg/EvUuAD4QvS
      name: Tempo Discord Server

markdown_extensions:
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
