site_name: Tempo
site_url: https://tempo-organization.github.io/tempo-cli/

theme:
  name: material
  features:
    - navigation.tabs
  icon:
    logo: fontawesome/solid/t
    repo: fontawesome/brands/github
  palette:
    # Auto toggle for the user to switch between modes based on system preference
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to system preference

    # Default Dark Mode (for users who have dark mode preference)
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Dark mode
      primary: deep purple
      accent: cyan

    # Default Light Mode (for users who have light mode preference)
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/weather-night
        name: Light mode
      primary: deep purple
      accent: cyan

nav:
  - Home: index.md
  - Getting Started: "getting_started.md"
  - Tutorials: tutorials.md
  - Reference: reference.md
  - FAQ: faq.md
  - Roadmap: to_do_list.md
  - Community: community.md

extra_css:
  - stylesheets/extra.css

repo_url: https://github.com/Tempo-Organization/tempo-cli
repo_name: tempo

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Tempo-Organization/tempo-cli
      name: Tempo on Github
    - icon: fontawesome/brands/discord
      link: https://discord.gg/EvUuAD4QvS
      name: Tempo Discord Server
