site_name: UnrealAutoMod
site_url: https://mythical-github.github.io/unreal_auto_mod/

theme:
  name: material
  features:
    - navigation.tabs
  icon:
    logo: fontawesome/solid/u
    repo: fontawesome/brands/github
  palette:
    # Auto toggle for the user to switch between modes based on system preference
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to system preference

    # Default Dark Mode (for users who have dark mode preference)
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Dark mode
      primary: deep purple
      accent: cyan

    # Default Light Mode (for users who have light mode preference)
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/weather-night
        name: Light mode
      primary: deep purple
      accent: cyan

nav:
  - Home: index.md
  - Getting Started: getting_started.md
  - Setup: setup.md
  - Tutorials: tutorials.md
  - Projects: projects.md
  - Reference: reference.md
  - API: api.md
  - How to: how_to.md
  - FAQ: faq.md
  - Roadmap:
      - Main: to_do_lists/main.md
      - Settings: to_do_lists/settings.md
      - Iostore: to_do_lists/Iostore.md
      - Documentation: to_do_lists/documentation.md
      - Later Later: to_do_lists/later_later.md
      - Later Later Later: to_do_lists/later_later_later.md
      - Sooner Later: to_do_lists/sooner_later.md
  - Community: community.md
  - Blog: blog.md

  
extra_css:
  - stylesheets/extra.css

repo_url: https://github.com/Mythical-Github/unreal_auto_mod
repo_name: unreal_auto_mod

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Mythical-Github/unreal_auto_mod
      name: UnrealAutoMod on Github
    - icon: fontawesome/brands/discord
      link: https://discord.gg/EvUuAD4QvS
      name: UnrealAutoMod Discord Server
